# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MWindow.ui'
#
# Created: Mon May 21 23:40:58 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MWindow(object):
    def setupUi(self, MWindow):
        MWindow.setObjectName(_fromUtf8("MWindow"))
        MWindow.resize(600, 500)
        self.verticalLayout = QtGui.QVBoxLayout(MWindow)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(MWindow)
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.page)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.btn_load_image = QtGui.QPushButton(self.page)
        self.btn_load_image.setObjectName(_fromUtf8("btn_load_image"))
        self.verticalLayout_2.addWidget(self.btn_load_image)
        self.image_preview = QtGui.QGraphicsView(self.page)
        self.image_preview.setObjectName(_fromUtf8("image_preview"))
        self.verticalLayout_2.addWidget(self.image_preview)
        self.btn_next1 = QtGui.QPushButton(self.page)
        self.btn_next1.setEnabled(False)
        self.btn_next1.setObjectName(_fromUtf8("btn_next1"))
        self.verticalLayout_2.addWidget(self.btn_next1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.page_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_4 = QtGui.QLabel(self.page_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.page_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.page_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.txt_v_parts = QtGui.QSpinBox(self.page_2)
        self.txt_v_parts.setMinimum(1)
        self.txt_v_parts.setMaximum(99999)
        self.txt_v_parts.setObjectName(_fromUtf8("txt_v_parts"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txt_v_parts)
        self.txt_h_parts = QtGui.QSpinBox(self.page_2)
        self.txt_h_parts.setMinimum(1)
        self.txt_h_parts.setMaximum(99999)
        self.txt_h_parts.setObjectName(_fromUtf8("txt_h_parts"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txt_h_parts)
        self.txt_max_error = QtGui.QDoubleSpinBox(self.page_2)
        self.txt_max_error.setMaximum(100.0)
        self.txt_max_error.setSingleStep(0.01)
        self.txt_max_error.setProperty("value", 5.0)
        self.txt_max_error.setObjectName(_fromUtf8("txt_max_error"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txt_max_error)
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.txt_zip = QtGui.QSpinBox(self.page_2)
        self.txt_zip.setMinimum(1)
        self.txt_zip.setMaximum(999999)
        self.txt_zip.setProperty("value", 21)
        self.txt_zip.setObjectName(_fromUtf8("txt_zip"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txt_zip)
        self.verticalLayout_3.addLayout(self.formLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.progressBar = QtGui.QProgressBar(self.page_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_3.addWidget(self.progressBar)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btn_back2 = QtGui.QPushButton(self.page_2)
        self.btn_back2.setObjectName(_fromUtf8("btn_back2"))
        self.horizontalLayout.addWidget(self.btn_back2)
        self.btn_next2 = QtGui.QPushButton(self.page_2)
        self.btn_next2.setEnabled(True)
        self.btn_next2.setObjectName(_fromUtf8("btn_next2"))
        self.horizontalLayout.addWidget(self.btn_next2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.page_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.before = QtGui.QGraphicsView(self.page_3)
        self.before.setObjectName(_fromUtf8("before"))
        self.horizontalLayout_2.addWidget(self.before)
        self.after = QtGui.QGraphicsView(self.page_3)
        self.after.setObjectName(_fromUtf8("after"))
        self.horizontalLayout_2.addWidget(self.after)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(MWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MWindow)

    def retranslateUi(self, MWindow):
        MWindow.setWindowTitle(QtGui.QApplication.translate("MWindow", "Главное окно", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MWindow", "<b>Подготовка</b> / Настройка / Результат", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_load_image.setText(QtGui.QApplication.translate("MWindow", "Выбрать изображение", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_next1.setText(QtGui.QApplication.translate("MWindow", "Далее >>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MWindow", "Подготовка / <b>Настройка</b> / Результат", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MWindow", "Разбиений по вертикали", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MWindow", "Разбиений по горизонтали", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MWindow", "Максимальная ошибка", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MWindow", "Нейронов на скрытом слое", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_back2.setText(QtGui.QApplication.translate("MWindow", "<< Назад", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_next2.setText(QtGui.QApplication.translate("MWindow", "Далее >>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MWindow", "Подготовка / Настройка / <b>Результат</b>", None, QtGui.QApplication.UnicodeUTF8))

